![title](http://oi65.tinypic.com/2nvf248.jpg)

![title](http://i66.tinypic.com/qofw5h.jpg)

The model had an easier time interpreting the engineered features. What's nice is that this feature engineering method not only improves performance, but it does it in a logical way that humans can understand. http://blog.davidkaleko.com/feature-engineering-cyclical-features.html

In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("hour.csv")

In [42]:
df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,28,1/2/11,1,0,1,3,0,0,0,2,0.46,0.4545,0.94,0.1940,2,4,6
1,29,1/2/11,1,0,2,4,0,0,0,2,0.46,0.4545,0.94,0.1940,2,1,3
2,30,1/2/11,1,0,3,6,0,0,0,3,0.42,0.4242,0.77,0.2985,0,2,2
3,31,1/2/11,1,0,4,7,0,0,0,2,0.40,0.4091,0.76,0.1940,0,1,1
4,32,1/2/11,1,0,5,8,0,0,0,3,0.40,0.4091,0.71,0.2239,0,8,8

In [43]:
df = df[['mnth','hr','cnt']].copy()

In [44]:
df.head()

   mnth  hr  cnt
0     1   3    6
1     2   4    3
2     3   6    2
3     4   7    1
4     5   8    8

# in Predictive Maintenance, we have day/month/(year)

In [59]:
import numpy as np
df['hr_sin'] = np.sin(df.hr*(2.*np.pi/24))
df['hr_cos'] = np.cos(df.hr*(2.*np.pi/24))
df['mnth_sin'] = np.sin((df.mnth-1)*(2.*np.pi/12))
df['mnth_cos'] = np.cos((df.mnth-1)*(2.*np.pi/12))

In [61]:
df.head(33)

    mnth  hr  cnt        hr_sin        hr_cos      mnth_sin      mnth_cos
0      1   3    6  7.071068e-01  7.071068e-01  0.000000e+00  1.000000e+00
1      2   4    3  8.660254e-01  5.000000e-01  5.000000e-01  8.660254e-01
2      3   6    2  1.000000e+00  6.123234e-17  8.660254e-01  5.000000e-01
3      4   7    1  9.659258e-01 -2.588190e-01  1.000000e+00  6.123234e-17
4      5   8    8  8.660254e-01 -5.000000e-01  8.660254e-01 -5.000000e-01
5      6   9   20  7.071068e-01 -7.071068e-01  5.000000e-01 -8.660254e-01
6      7  10   53  5.000000e-01 -8.660254e-01  1.224647e-16 -1.000000e+00
7      8  11   70  2.588190e-01 -9.659258e-01 -5.000000e-01 -8.660254e-01
8      9  12   93  1.224647e-16 -1.000000e+00 -8.660254e-01 -5.000000e-01
9     10  13   75 -2.588190e-01 -9.659258e-01 -1.000000e+00 -1.836970e-16
10    11  14   59 -5.000000e-01 -8.660254e-01 -8.660254e-01  5.000000e-01
11    12  15   74 -7.071068e-01 -7.071068e-01 -5.000000e-01  8.660254e-01
12    13  16   76 -8.660254e-01 -5.000000e-01 -2.449294e-16  1.000000e+00
13    14  17   65 -9.659258e-01 -2.588190e-01  5.000000e-01  8.660254e-01
14    15  18   53 -1.000000e+00 -1.836970e-16  8.660254e-01  5.000000e-01
15    16  19   30 -9.659258e-01  2.588190e-01  1.000000e+00  1.194340e-15
16    17  20   22 -8.660254e-01  5.000000e-01  8.660254e-01 -5.000000e-01
17    18  21   31 -7.071068e-01  7.071068e-01  5.000000e-01 -8.660254e-01
18    19  22    9 -5.000000e-01  8.660254e-01  3.673940e-16 -1.000000e+00
19    20  23    8 -2.588190e-01  9.659258e-01 -5.000000e-01 -8.660254e-01
20    21   0    5  0.000000e+00  1.000000e+00 -8.660254e-01 -5.000000e-01
21    22   1    2  2.588190e-01  9.659258e-01 -1.000000e+00 -4.286264e-16
22    23   4    1  8.660254e-01  5.000000e-01 -8.660254e-01  5.000000e-01
23    24   5    3  9.659258e-01  2.588190e-01 -5.000000e-01  8.660254e-01
24     1   6   30  1.000000e+00  6.123234e-17  0.000000e+00  1.000000e+00
25     2   7   64  9.659258e-01 -2.588190e-01  5.000000e-01  8.660254e-01
26     3   8  154  8.660254e-01 -5.000000e-01  8.660254e-01  5.000000e-01
27     1   9   88  7.071068e-01 -7.071068e-01  0.000000e+00  1.000000e+00
28     1  10   44  5.000000e-01 -8.660254e-01  0.000000e+00  1.000000e+00
29     1  11   51  2.588190e-01 -9.659258e-01  0.000000e+00  1.000000e+00
30     1  12   61  1.224647e-16 -1.000000e+00  0.000000e+00  1.000000e+00
31     1  13   61 -2.588190e-01 -9.659258e-01  0.000000e+00  1.000000e+00
32     1  14   77 -5.000000e-01 -8.660254e-01  0.000000e+00  1.000000e+00